/** Публичные статические маршруты для sitemap (с trailing slash). */
export const PUBLIC_STATIC_ROUTES = [
  "/",
  "/catalog/",
  "/company/",
  "/company/contacts/",
  "/company/requisites/",
  "/company/vacancy/",
  "/company/partners/",
  "/help/",
  "/help/delivery/",
  "/help/refund/",
  "/help/terms/",
  "/gifts/",
  "/new/",
  "/landings/",
  "/lookbooks/",
  "/legal/privacy/",
  "/legal/offer/",
] as const;
